### ISSUE TITLE
Error prefix is not defined

### ISSUE THREAD

**Issue by lukaas33** [genome/docker-bam_readcount_helper-cwl#11]
The docker image 1.1.1 has the helper python script but it is not the same.

Mainly it contains these lines:
```
if prefix == 'NOPREFIX':
    prefixed_sample = sample
else:
    prefixed_sample = '_'.join([prefix, sample])
    ```
   
This causes an error since prefix is not defined

**Comment by susannasiebert** [comment]
Are you looking at the correct branch? This repo is set up to have a branch matching each docker release. The master branch is not maintained. E.g. the 1.1.1 release branch is [here](https://github.com/genome/docker-bam_readcount_helper-cwl/tree/1.1.1).

**Comment by lukaas33** [comment]
Hi @susannasiebert , in this release the python file throws an error at this line https://github.com/genome/docker-bam_readcount_helper-cwl/blob/fbf3eaf7fc3a6831a43923eed799e49703175464/bam_readcount_helper.py#L46 

I now download the file that is in the main branch and execute that. So far it seems to be working but I do not have any results yet after running for 8 hours so I am not sure.

**Comment by susannasiebert** [comment]
the prefix variable is simply one of the command line arguments so I'm surprised you are seeing an error with it not being defined since it gets parsed in all of the conditions from lines 39-44. My only explanation is that maybe you are submitting less arguments than expected, which is not being caught, and so your run doesn't enter any of these if-else clauses and none of the command line arguments are being parsed. Without knowing your exact argument, I can't confirm though. Can you please post how you were trying to use this script when you encountered this error?

**Comment by lukaas33** [comment]
Hi,

The command that i was trying was:
`bam_readcount_helper decomp.vcf sample ref.fa rna.bam output/`

I based this on the pVACtools docs as there were no docs in this repo. That is why I was confused by the error, but I could have looked at the script in more detail to find out I need to do something like:

`bam_readcount_helper decomp.vcf sample ref.fa rna.bam prefix output/`

which is what I am running now

**Comment by susannasiebert** [comment]
Thank you for pointing that out. We made the prefix addition after we wrote the pvacseq docs. I will update the example command.

**Comment by susannasiebert** [comment]
pVACtools docs have been updated to fix the bam_readcount_helper example command. Closing.
